INSERT INTO escuela.catalogos (ID, DESCRIPTION, TYPE, ID_ROOT) VALUES (1, 'Universidad Tecnológica de Nezahualcóyotl', 'UNIVERSIDAD', null);
INSERT INTO escuela.catalogos (ID, DESCRIPTION, TYPE, ID_ROOT) VALUES (2, 'Ingeniería Ambiental y Sustentabilidad', 'INGENIERIA', 1);
INSERT INTO escuela.catalogos (ID, DESCRIPTION, TYPE, ID_ROOT) VALUES (3, 'Ingeniería Industrial', 'INGENIERIA', 1);
INSERT INTO escuela.catalogos (ID, DESCRIPTION, TYPE, ID_ROOT) VALUES (4, 'Ingeniería en Tecnologías de la Información e Innovación Digital', 'INGENIERIA', 1);
INSERT INTO escuela.catalogos (ID, DESCRIPTION, TYPE, ID_ROOT) VALUES (5, 'Ingeniería Mecatrónica', 'INGENIERIA', 1);
INSERT INTO escuela.catalogos (ID, DESCRIPTION, TYPE, ID_ROOT) VALUES (6, 'Ingeniería Aeronáutica en Mantenimiento', 'INGENIERIA', 1);
INSERT INTO escuela.catalogos (ID, DESCRIPTION, TYPE, ID_ROOT) VALUES (7, 'Técnico Superior Universitario en Gestión Ambiental', 'TSU', 2);
INSERT INTO escuela.catalogos (ID, DESCRIPTION, TYPE, ID_ROOT) VALUES (8, 'Técnico Superior Universitario en Procesos Productivos', 'TSU', 3);
INSERT INTO escuela.catalogos (ID, DESCRIPTION, TYPE, ID_ROOT) VALUES (9, 'Técnico Superior Universitario en Desarrollo de Software Multiplataforma', 'TSU', 4);
INSERT INTO escuela.catalogos (ID, DESCRIPTION, TYPE, ID_ROOT) VALUES (10, 'Técnico Superior Universitario en Entornos Virtuales y Negocios Digitales', 'TSU', 4);
INSERT INTO escuela.catalogos (ID, DESCRIPTION, TYPE, ID_ROOT) VALUES (11, 'Técnico Superior Universitario en Infraestructura de Redes Digitales', 'TSU', 4);
INSERT INTO escuela.catalogos (ID, DESCRIPTION, TYPE, ID_ROOT) VALUES (12, 'Técnico Superior Universitario en Sistemas de Manufactura Flexible', 'TSU', 5);
INSERT INTO escuela.catalogos (ID, DESCRIPTION, TYPE, ID_ROOT) VALUES (13, 'Técnico Superior Universitario en Mantenimiento de Sistemas Electrónicos de las Aeronaves', 'TSU', 6);
